/**
 * Generate `src/run/routes.gen.ts` from the orchestrator's OpenAPI document.
 *
 * The console used to name every path as a string literal at 45 call sites. A route renamed on the
 * server then failed at RUNTIME, as an empty panel three files from the cause. Generating the paths
 * makes that a compile error instead.
 *
 *   node scripts/generate-routes.mjs [path/to/openapi.json]
 *
 * The default is the sibling kontra checkout, the same shape `@kontra/core` is already linked from.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const spec = process.argv[2] ?? join(here, '..', '..', 'kontra', 'docs', 'openapi.json');
const doc = JSON.parse(readFileSync(spec, 'utf8'));

const entries = [];
for (const [path, ops] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(ops)) {
    entries.push({ id: op.operationId, method: method.toUpperCase(), path, open: (op.security ?? []).length === 0 });
  }
}
entries.sort((a, b) => a.id.localeCompare(b.id));

const body = `// GENERATED by scripts/generate-routes.mjs from the orchestrator's OpenAPI document.
// DO NOT EDIT. Run \`node scripts/generate-routes.mjs\` after the server's routes change;
// \`routes.gen.test.ts\` is what fails if you forget.
//
// WHY THIS EXISTS. Forty-five hand-written path literals meant a route renamed on the server failed
// at runtime — an empty panel, three files from the cause. A generated table makes it a compile
// error.

/** Every route the orchestrator serves, by operation id. */
export const ROUTES = {
${entries.map((e) => `  ${e.id}: { method: '${e.method}', path: '${e.path}', open: ${e.open} },`).join('\n')}
} as const;

export type OperationId = keyof typeof ROUTES;

/** Every path template the server serves — what a call-site guard checks a literal against. */
export const API_PATHS: readonly string[] = Object.freeze(
  Array.from(new Set(Object.values(ROUTES).map((r) => r.path)))
);

/**
 * Fill a path template's \`{param}\` holes.
 *
 * Values are percent-encoded, which is not a nicety: a dataset name or a run id can contain a
 * slash, and an unencoded one silently addresses a different route.
 */
export function apiPath(id: OperationId, params: Record<string, string | number> = {}): string {
  return ROUTES[id].path.replace(/\\{([A-Za-z0-9_]+)\\}/g, (_, key) => {
    const v = params[key];
    if (v === undefined) throw new Error(\`apiPath(\${id}): missing path parameter \${key}\`);
    return encodeURIComponent(String(v));
  });
}
`;
const out = join(here, '..', 'src', 'run', 'routes.gen.ts');
writeFileSync(out, body);
console.log(`${out} — ${entries.length} operations, ${new Set(entries.map((e) => e.path)).size} paths`);
