// GENERATED by scripts/generate-routes.mjs from the orchestrator's OpenAPI document.
// DO NOT EDIT. Run `node scripts/generate-routes.mjs` after the server's routes change;
// `routes.gen.test.ts` is what fails if you forget.
//
// WHY THIS EXISTS. Forty-five hand-written path literals meant a route renamed on the server failed
// at runtime — an empty panel, three files from the cause. A generated table makes it a compile
// error.

/** Every route the orchestrator serves, by operation id. */
export const ROUTES = {
  deleteActorsByKey: { method: 'DELETE', path: '/api/actors/{key}', open: true },
  deleteDatasetsByName: { method: 'DELETE', path: '/api/datasets/{name}', open: true },
  deleteDatasetsRunsByRunIdName: { method: 'DELETE', path: '/api/datasets/runs/{runId}/name', open: false },
  deleteDatasetsRunsByRunIdTagsByTag: { method: 'DELETE', path: '/api/datasets/runs/{runId}/tags/{tag}', open: false },
  deleteGraphsById: { method: 'DELETE', path: '/api/graphs/{id}', open: true },
  deleteScratchById: { method: 'DELETE', path: '/api/scratch/{id}', open: true },
  deleteSecretsByName: { method: 'DELETE', path: '/api/secrets/{name}', open: true },
  deleteSlotsActorByActorBySlot: { method: 'DELETE', path: '/api/slots/actor/{actor}/{slot}', open: true },
  deleteSourcesByKindById: { method: 'DELETE', path: '/api/sources/{kind}/{id}', open: false },
  getActors: { method: 'GET', path: '/api/actors', open: true },
  getDatasets: { method: 'GET', path: '/api/datasets', open: true },
  getDatasetsByNamePreview: { method: 'GET', path: '/api/datasets/{name}/preview', open: true },
  getDatasetsByNameProvenance: { method: 'GET', path: '/api/datasets/{name}/provenance', open: true },
  getDatasetsExport: { method: 'GET', path: '/api/datasets/export', open: true },
  getDatasetsRetentionPreview: { method: 'GET', path: '/api/datasets/retention/preview', open: true },
  getDatasetsRowsStream: { method: 'GET', path: '/api/datasets/rows/stream', open: true },
  getDatasetsRuns: { method: 'GET', path: '/api/datasets/runs', open: false },
  getDatasetsSchema: { method: 'GET', path: '/api/datasets/schema', open: true },
  getFleetOperations: { method: 'GET', path: '/api/fleet/operations', open: false },
  getGraphs: { method: 'GET', path: '/api/graphs', open: true },
  getGraphsById: { method: 'GET', path: '/api/graphs/{id}', open: true },
  getHealth: { method: 'GET', path: '/api/health', open: true },
  getInfraOpsByFqn: { method: 'GET', path: '/api/infra/ops/{fqn}', open: false },
  getInfraStacks: { method: 'GET', path: '/api/infra/stacks', open: false },
  getInfraStacksByFqnLeases: { method: 'GET', path: '/api/infra/stacks/{fqn}/leases', open: false },
  getInfraStacksByFqnState: { method: 'GET', path: '/api/infra/stacks/{fqn}/state', open: false },
  getLogin: { method: 'GET', path: '/api/login', open: true },
  getPanelsTerminals: { method: 'GET', path: '/api/panels/terminals', open: true },
  getProbesByRunId: { method: 'GET', path: '/api/probes/{runId}', open: false },
  getPulse: { method: 'GET', path: '/api/pulse', open: true },
  getQueuesByQueuePollers: { method: 'GET', path: '/api/queues/{queue}/pollers', open: true },
  getRuns: { method: 'GET', path: '/api/runs', open: false },
  getRunsByRunId: { method: 'GET', path: '/api/runs/{runId}', open: false },
  getRunsByRunIdAsks: { method: 'GET', path: '/api/runs/{runId}/asks', open: false },
  getRunsByRunIdExplore: { method: 'GET', path: '/api/runs/{runId}/explore', open: false },
  getRunsByRunIdHeartbeats: { method: 'GET', path: '/api/runs/{runId}/heartbeats', open: false },
  getRunsByRunIdHistory: { method: 'GET', path: '/api/runs/{runId}/history', open: false },
  getRunsByRunIdPhase: { method: 'GET', path: '/api/runs/{runId}/phase', open: false },
  getRunsByRunIdProgress: { method: 'GET', path: '/api/runs/{runId}/progress', open: false },
  getRunsByRunIdStream: { method: 'GET', path: '/api/runs/{runId}/stream', open: false },
  getScratch: { method: 'GET', path: '/api/scratch', open: true },
  getScratchById: { method: 'GET', path: '/api/scratch/{id}', open: true },
  getScratchByIdSpec: { method: 'GET', path: '/api/scratch/{id}/spec', open: true },
  getSecrets: { method: 'GET', path: '/api/secrets', open: true },
  getSecretsByName: { method: 'GET', path: '/api/secrets/{name}', open: true },
  getSlots: { method: 'GET', path: '/api/slots', open: true },
  getSlotsActorByActor: { method: 'GET', path: '/api/slots/actor/{actor}', open: true },
  getSlotsAudit: { method: 'GET', path: '/api/slots/audit', open: true },
  getSourcesActorByIdSchema: { method: 'GET', path: '/api/sources/actor/{id}/schema', open: false },
  getSourcesActorByIdSchemaStream: { method: 'GET', path: '/api/sources/actor/{id}/schema/stream', open: false },
  getSourcesByKind: { method: 'GET', path: '/api/sources/{kind}', open: false },
  getSourcesByKindByIdFile: { method: 'GET', path: '/api/sources/{kind}/{id}/file', open: false },
  getSourcesByKindByIdFiles: { method: 'GET', path: '/api/sources/{kind}/{id}/files', open: false },
  getStateByTier: { method: 'GET', path: '/api/state/{tier}', open: true },
  getStuck: { method: 'GET', path: '/api/stuck', open: true },
  getSummariesHealth: { method: 'GET', path: '/api/summaries/health', open: true },
  getSummariesHourly: { method: 'GET', path: '/api/summaries/hourly', open: true },
  getSummariesRunsByRunId: { method: 'GET', path: '/api/summaries/runs/{runId}', open: true },
  getWorkflows: { method: 'GET', path: '/api/workflows', open: true },
  getWorkflowsExposure: { method: 'GET', path: '/api/workflows/exposure', open: true },
  getWorkflowsFileByName: { method: 'GET', path: '/api/workflows/file/{name}', open: true },
  getWorkspaces: { method: 'GET', path: '/api/workspaces', open: true },
  postActors: { method: 'POST', path: '/api/actors', open: true },
  postActorsByKeyDigest: { method: 'POST', path: '/api/actors/{key}/digest', open: true },
  postDatasetsQuery: { method: 'POST', path: '/api/datasets/query', open: false },
  postDatasetsRunsByRunIdTags: { method: 'POST', path: '/api/datasets/runs/{runId}/tags', open: false },
  postGraphs: { method: 'POST', path: '/api/graphs', open: true },
  postInfraStacksByFqnByOp: { method: 'POST', path: '/api/infra/stacks/{fqn}/{op}', open: false },
  postLogin: { method: 'POST', path: '/api/login', open: true },
  postLogout: { method: 'POST', path: '/api/logout', open: true },
  postPanelsReport: { method: 'POST', path: '/api/panels/report', open: true },
  postPanelsTicket: { method: 'POST', path: '/api/panels/ticket', open: true },
  postRuns: { method: 'POST', path: '/api/runs', open: false },
  postRunsByRunIdAsksByAskId: { method: 'POST', path: '/api/runs/{runId}/asks/{askId}', open: false },
  postRunsByRunIdProgress: { method: 'POST', path: '/api/runs/{runId}/progress', open: false },
  postRunsByRunIdStop: { method: 'POST', path: '/api/runs/{runId}/stop', open: false },
  postScratch: { method: 'POST', path: '/api/scratch', open: true },
  postSecretsByNameVersionsByVersionRevoke: { method: 'POST', path: '/api/secrets/{name}/versions/{version}/revoke', open: true },
  postSecretsIdentity: { method: 'POST', path: '/api/secrets/identity', open: true },
  postSecretsResolve: { method: 'POST', path: '/api/secrets/resolve', open: false },
  postSlotsDeclare: { method: 'POST', path: '/api/slots/declare', open: true },
  postSlotsPreflight: { method: 'POST', path: '/api/slots/preflight', open: true },
  postSlotsResolve: { method: 'POST', path: '/api/slots/resolve', open: false },
  postSourcesActorByIdCaller: { method: 'POST', path: '/api/sources/actor/{id}/caller', open: false },
  postSourcesActorByIdProbe: { method: 'POST', path: '/api/sources/actor/{id}/probe', open: false },
  postSourcesActorByIdServe: { method: 'POST', path: '/api/sources/actor/{id}/serve', open: false },
  postSourcesByKind: { method: 'POST', path: '/api/sources/{kind}', open: false },
  postUploads: { method: 'POST', path: '/api/uploads', open: false },
  postWorkflowsCatalog: { method: 'POST', path: '/api/workflows/catalog', open: true },
  postWorkflowsFileByNamePause: { method: 'POST', path: '/api/workflows/file/{name}/pause', open: true },
  postWorkflowsFileByNameResume: { method: 'POST', path: '/api/workflows/file/{name}/resume', open: true },
  postWorkflowsServe: { method: 'POST', path: '/api/workflows/serve', open: false },
  postWorkspaces: { method: 'POST', path: '/api/workspaces', open: true },
  putDatasetsRunsByRunIdName: { method: 'PUT', path: '/api/datasets/runs/{runId}/name', open: false },
  putRunsByRunIdWorkflow: { method: 'PUT', path: '/api/runs/{runId}/workflow', open: false },
  putSecretsByName: { method: 'PUT', path: '/api/secrets/{name}', open: true },
  putSlotsActorByActorBySlot: { method: 'PUT', path: '/api/slots/actor/{actor}/{slot}', open: true },
  putWorkspacesCurrent: { method: 'PUT', path: '/api/workspaces/current', open: true },
} as const;

export type OperationId = keyof typeof ROUTES;

/** Every path template the server serves — what a call-site guard checks a literal against. */
export const API_PATHS: readonly string[] = Object.freeze(
  Array.from(new Set(Object.values(ROUTES).map((r) => r.path)))
);

/**
 * Fill a path template's `{param}` holes.
 *
 * Values are percent-encoded, which is not a nicety: a dataset name or a run id can contain a
 * slash, and an unencoded one silently addresses a different route.
 */
export function apiPath(id: OperationId, params: Record<string, string | number> = {}): string {
  return ROUTES[id].path.replace(/\{([A-Za-z0-9_]+)\}/g, (_, key) => {
    const v = params[key];
    if (v === undefined) throw new Error(`apiPath(${id}): missing path parameter ${key}`);
    return encodeURIComponent(String(v));
  });
}
